name: Build SMS App APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install -g cordova
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
    - uses: android-actions/setup-android@v3
    - run: cordova platform add android
    - run: cordova plugin add cordova-plugin-sms
    - run: cordova build android --release
    - uses: actions/upload-artifact@v3
      with:
        name: sms-app-release
        path: platforms/android/app/build/outputs/apk/release/app-release.apk